### ISSUE TITLE
Remove the concept of `Async` from core library

### ISSUE THREAD

**Issue by hellohuanlin** [airbnb/MvRx#141]
A couple reasons: 

1. Async doesn't feel like something "core" to MvRx. We can simply have `execute` to take 3 callbacks like: 
```
execute(onLoading={}, onSuccess={}, onFail={})
```
2. Async contains a case that will never happen
```
execute { async -> 
  when (async) {
    Uninitialized -> // this is never happen
    is Success, is Fail, Loading -> // this is valid
  }
}
```
This is unreachable code, but has to be here to make compiler happy, which is ugly

3. Async doesn't describe all cases well. For example, I need to have the `Fail` to contain an associated value. or have the `Loading` state to contain something else, etc. Having Async in the library may mislead developers in such scenarios. 

@BenSchwab @elihart @gpeal

**Comment by elihart** [comment]
I don't feel that it should be removed from the library, it could be made optional so there is an execute function with the specific lambdas you mentioned.

**Comment by gpeal** [comment]
@hellohuanlin I also don't think it should be removed as it makes MvRx work well for most cases out of the box and it seems to be working well for most people.

It's also very small so it doesn't bloat the library and it's easy enough for you to make your own equivalent for your use case since MvRx isn't coupled to it in any way.

**Comment by hellohuanlin** [comment]
Do you think it's better design if `execute(onLoading={}, onSuccess={}, onFail={})` is provided as first class API (since unlike Async, it describes exactly what the API does), and have the existing `Async` API as second class wrapper API?

**Comment by elihart** [comment]
can't we have an `execute` extension function to provide the signature you're suggesting? since they have different argument signatures they can coexist. There's nothing preventing somebody from creating that extension in their own project if they like

One downside to offering it in the mvrx library is that it adds another way to do things. New users see two options and they don't know which to use - "when do you use Async?"

With Epoxy I created a library with a ton of flexibility and control, and not a lot of opinionated structure on the right way to use it. This has created a ton of questions and issues from people wanting to start using the library and not sure what the right way is.

`Async` is nice because it works well for a large majority of cases, provides a lot of help for little extra code, and is integrated into mvrx in an opinionated way to make it easy for new users.

I'd prefer to allow power users to define their own extensions if they want to

**Comment by hellohuanlin** [comment]
@elihart yes we can do that. But it's not about my own project. From the whole pipeline, it's a bit odd to have `Async` as the first class API, and the func with 3 callbacks, (which *exactly* describes what the API does) to be powered by Async. The opposite feels more natural to me.

**Comment by gpeal** [comment]
@hellohuanlin What exactly do you propose?

**Comment by gpeal** [comment]
@hellohuanlin What is the advantage of that? You could also unfurl the current execute reducer and instead of setting state to something like `copy(foo = it)`, you could do whatever you want.

**Comment by hellohuanlin** [comment]
@gpeal closing this issue now. I will have an abstraction layer on top of mvrx to have better control of the code.
