### ISSUE TITLE
Jetpack Compose vs MvRx

### ISSUE THREAD

**Issue by qbait** [airbnb/MvRx#241]
What do you think about Jetpack Compose?
Would you use MvRx in a greenfield project knowing that the native solution from Google will be production ready soon?

**Comment by semanticer** [comment]
Jetback Compose is currently not even in alpha - I guess it will take minimally a year before it's production ready.

**Comment by Swirastlynn** [comment]
Ok, assume it's June 2020 right now. What then?

**Comment by gpeal** [comment]
@qbait @Swirastlynn I think it's too early to really know yet. Compose looks fantastic and we're excited to see how it evolves. One of the core Compose team members is a former Airbnb-er so we'll certainly work together as it evolves.

At a high level, Compose is primarily a replacement for the view hierarchy and secondarily, state management with `@Model`. It should be possible to use MvRx for state management and Compose for UI because they both stem from very similar declarative and reactive principles.

**Comment by kaushalyap** [comment]
@gpeal Since Compose 1.0 alpha was released, Do we still need MvRx?

**Comment by gpeal** [comment]
@kaushalyap Definitely! They are solving different kinds of problems. There are still good reasons to keep the business logic and data storage/persistence/retrieval in a separate place. There is a good reason that Google made specific vanilla ViewModel integration ([docs](https://developer.android.com/jetpack/compose/interop#viewmodel)) and we're looking into doing the same for MvRx.
