### ISSUE TITLE
How to force refresh ui in an inactive activity ?

### ISSUE THREAD

**Issue by lwj1994** [airbnb/MvRx#252]
I built a video list using mvrx. I came across a scene where I paused the video on onpause() . But when I press the home button, mvrx will not refresh ui, the video is still playing. I guess, when I press the home button, the Activity has entered the background, not active, so mvrx does not respond.

**Comment by tasomaniac** [comment]
Currently, there is no way to get notified about state changes in the UI (Fragment or Activity) when the screen is not active. Doing this is kind of against what MvRx is trying to do. 

Imagine your `MvRx` state as a representation of what your users see when they are actively have the screen visible. Using clicking the `pause` button would pause the video by changing the state. But lifecycle can be seen as different since you want to resume when the screen comes back.

**Comment by lwj1994** [comment]
> Currently, there is no way to get notified about state changes in the UI (Fragment or Activity) when the screen is not active. Doing this is kind of against what MvRx is trying to do.
> 
> Imagine your `MvRx` state as a representation of what your users see when they are actively have the screen visible. Using clicking the `pause` button would pause the video by changing the state. But lifecycle can be seen as different since you want to resume when the scr
