### ISSUE TITLE
MvRx and Coroutines

### ISSUE THREAD

**Issue by qbait** [airbnb/MvRx#293]
I have a possibility to rewrite an app from scratch and decided to use `MvRx` :)
Personally, I prefer `Coroutines` over `RxJava`. Are you guys planning to release `MvRx` based on `Coroutines`?

**Comment by elihart** [comment]
There are two main, different ways that mvrx can interact with coroutines.

Once is the implementation of the state store.  This implementation is not exposed to you, so it doesn't really matter which implementation is used (beyond bringing in the dependency on Rx.) we could add official support for a coroutine version (like https://github.com/airbnb/MvRx/pull/84) but it isn't a priority since the implementation detail doens't matter much. The  state store is also customizable, you could implement your own coroutine based state store via the  mvrx state store interface and use that in all your viewmodels.

The other is using coroutines to run async code in the viewmodel, and subscribing to those async calls with `execute`. We will likely support this soonish, but this is also something that you can add support for in your own viewmodel fairly easily, so there isn't much urgency here.

All you really need is a base viewmodel in your app that is setup like this
```
abstract class MvRxViewModel<S : MvRxState>(
    initialState: S
) : CoroutineScope by CoroutineScope(Dispatchers.getDefault() + SupervisorJob()), BaseMvRxViewModel<S>(

protected fun <T> Deferred<T>.execute(reducer: S.(Async<T>) -> S): Job {

        // Queue the loading immediately so that if any following function calls check this value it has been set.
        setState { reducer(Loading()) }

        return launch {
            val asyncValue: Async<T>? = try {
                Success(await())
            } catch (e: CancellationException) {
                // To match the behavior of disposing an Observable, we don't make any changes to state if the job is cancelled.
                null
            } catch (e: Exception) {
                Fail(e)
            }

            if (asyncValue != null) {
                setState { reducer(asyncValue) }
            }
        }
    }
```

**Comment by qbait** [comment]
Thanks @elihart !

**Comment by AndrazP** [comment]
@qbait Chris Beans' project Tivi is using MvRx and Coroutines
https://github.com/chrisbanes/tivi
