### ISSUE TITLE
The mvrx-launcher artifact is not available

### ISSUE THREAD

**Issue by pwillmann** [airbnb/MvRx#332]
I tried to use the new alpha version and noticed that the launcher artifact is not yet available as a maven repo.

Maybe this wiki page: https://github.com/airbnb/MvRx/wiki/MvRx-Launcher should clarify, that it's not yet available :).

**Comment by elihart** [comment]
This wasn't intended, so thanks for the bug report.

This is fixed with https://github.com/airbnb/MvRx/pull/282/commits/08efc557f8c45f9da0e2ae765c0490a57f77b53a

I am pushing a new release alpha2 right now that should fix it. Please try again (when the latest version is available) and let me know if you have any more problems :)

**Comment by elihart** [comment]
@THEAccess it is a separate artifact, you need to include `com.airbnb.android:mvrx-launcher`
