### ISSUE TITLE
Does the MvRxState object not persist beyond the life of a single activity / fragment?

### ISSUE THREAD

**Issue by eriegz** [airbnb/MvRx#416]
Like the title says, does the MvRxState object not persist beyond the life of a single fragment / activity? I.e.: can you not copy a value "123456" into a field "foo" of the MvRxState object from the view model of fragment "A" and then access it later from the view model of fragment "B"?

Right now I have a login fragment that copies the user response into a field `user: Async<UserResponse> = Uninitialized` and then navigates to a new fragment (and clears the back stack). From the login fragment, after I copy the user into the `user` field, I can see it there and everything seems fine. But after I navigate to the new fragment, when I try to access "user" from that fragment's view model, the `user` field is back to being "Uninitialized".

Am I missing something? If my question isn't clear then I can post some code snippets.

**Comment by gpeal** [comment]
@eriegz I don't follow your question. The MvRxViewModel follows the same lifecycle as a [Jetpack ViewModel](https://developer.android.com/topic/libraries/architecture/viewmodel#lifecycle). It never manually changes anything about your state either so if it gets reset, it's either because you manually reset it or somehow you have an entirely new Fragment (maybe from clearing the back stack and navigating to a new fragment)
