### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [airbnb/MvRx#91]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by gpeal** [comment]
@mansya you are welcome to propose some logos :) We have started to do some internal designs as well so we can't commit to anything but you are free to try 😃

**Comment by mansya** [comment]
hi sir. I have designed the logo for this project. What do you think ? do you like it ? if yes, which one do you like?
![mvrx](https://user-images.githubusercontent.com/33461607/46095276-55261c80-c1e6-11e8-9cd3-9fc804082189.png)

**Comment by C2H6O** [comment]
@mansya It's MvRx :)... Also, just wondering what is the inspiration for a house?

**Comment by mansya** [comment]
can the logo be like that? or have I contacted Mr. Again? I am happy to receive advice from you.

**Comment by gpeal** [comment]
@mansya ditty for @C2H6O's questions

**Comment by jQrgen** [comment]
Since there is no logo yet i'm using this one for my google developer group workshop :trollface: 
<img width="179" alt="screenshot 2018-11-15 at 14 58 41" src="https://user-images.githubusercontent.com/3964957/48557411-98476680-e8de-11e8-9fba-4271c5688c76.png">
https://www.gdgtrondheim.org/schedule/2018-11-19?sessionId=127
